---
driver:
  name: ssh

provisioner:
  name: chef_solo

platforms:
  - name: rhel-7.2

suites:
  - name: default
    run_list:
      - recipe[cockpit::default]
    attributes: {"cockpit":{"logintitle":"cockpit-test"}}
  - name: all_features
    run_list:
      - recipe[cockpit::features]
    attributes: {"cockpit":{"logintitle":"cockpit-test","features":{"pcp":true,"kubernetes":true}}}
