name 'cockpit'
maintainer 'colourmeamused'
maintainer_email '<maintainer> AT outlook com'
license 'agplv3'
description 'Installs/Configures cockpit'
long_description 'Installs/Configures cockpit (cockpit-project.org).
                  Initial support for RHEL 7.x'
version '0.1.0'
source_url 'https://github.com/colourmeamused/cockpit-cookbook.git'
issues_url 'https://github.com/colourmeamused/cockpit-cookbook/issues'
supports 'rhel', '>= 7.1'
depends 'redhat_subscription_manager', '~> 0.5'
depends 'firewalld'
